# Start the testnet server with the command 'docker-compose up -d'

troutsblog:
  build: ./production/
  dockerfile: Dockerfile
  container_name: troutsblog
  ports:
    - "3210:3210"  # <host port>:<container port>
    - "4001:4001"  # IPFS
  volumes:
    - ./ipfs-data:/home/safeuser/koa-ipfs-blog/ipfs-data
  restart: always

tor:
  image: goldy/tor-hidden-service
  container_name: tor-blog
  links:
    - troutsblog
  environment:
      TROUTSBLOG_PORTS: 80:3210 # Map port to detected service
  volumes:
    - ./keys:/var/lib/tor/hidden_service/
  restart: always
